"""
Executor node logic: Runs the code generated by the Analyst.
"""

from app.agent.state import AgentState
from app.agent.tools.code_runner import run_python_code


async def executor_node(state: AgentState) -> dict:
    """
    Executes the most recently generated code snippet.
    """
    snippets = state.get("code_snippets", [])
    if not snippets:
        return {"error": "No code snippets generated."}
        
    # Get the latest snippet
    # Since snippets is a list accumulated over the graph, the last one is the current one
    latest_snippet = snippets[-1]
    code = latest_snippet.get("code", "")
    file_id = state.get("file_id")
    
    print(f"⚙️ [Executor] Running code block (length: {len(code)})")
    
    # Run the code
    result = run_python_code(file_id, code)
    
    # Update the status of the snippet
    updated_snippet = {**latest_snippet}
    updated_snippet["status"] = "success" if result["success"] else "error"
    updated_snippet["stdout"] = result["stdout"]
    updated_snippet["stderr"] = result["stderr"]
    updated_snippet["execution_error"] = result["error"]
    
    # Because LangGraph's default for lists is usually append, returning code_snippets 
    # would append a duplicate. Instead, we can just edit the dict in place or return 
    # specific execution results back to the Evaluator. 
    # Wait, in the state reducer we used `operator.add` for lists. 
    # So we don't return code_snippets here to avoid duplicating it. We'll pass the execution result 
    # in a temporary key or handle it in the evaluator, or rely on mutation if references are maintained.
    # We will pass the `last_execution_result` to the state to let the Evaluator review it.
    
    visualizations = result.get("visualizations", [])
    if visualizations:
       for v in visualizations:
           v["title"] = latest_snippet.get("title", "Chart")

    updates = {
        "last_execution_result": result, # Transient — consumed by the Evaluator
    }
    
    if visualizations:
        updates["visualizations"] = visualizations # state reducer appends

    return updates
